CREATE TABLE CUSTOMER(
	CustomerID INT,
	NameCustomer VARCHAR(15) NOT NULL,
	LastNameCustomer VARCHAR(15) NOT NULL,
	PassCustomer VARCHAR(15) NOT NULL,
	Email VARCHAR(35) NOT NULL UNIQUE,
	Phone INT NOT NULL,
	StudentID INT DEFAULT 0 ,
	University VARCHAR(20),
	Miles INT DEFAULT 0,
	PRIMARY KEY (CustomerID)
	
);

CREATE TABLE WORKER(
	WorkerID INT,
	NameWorker VARCHAR(15) NOT NULL,
	LastNameWorker VARCHAR(15) NOT NULL,
	PassWorker VARCHAR(15) NOT NULL,
	PRIMARY KEY (WorkerID)
);

CREATE TABLE PLANE(
	PlaneID VARCHAR(6),
	Model VARCHAR(10) NOT NULL,
	PassengerCap INT NOT NULL,
	BagCap INT NOT NULL,
	PRIMARY KEY (PlaneID)

);

CREATE TABLE FLIGHT(
	FlightID VARCHAR(7),
	BagQuantity INT DEFAULT 0,
	UserQuantity INT DEFAULT 0,
	Gate INT NOT NULL,
	Departure TIMESTAMP NOT NULL, 
	Arrival TIMESTAMP NOT NULL,
	Origin VARCHAR(50) NOT NULL,
	Destination VARCHAR(50) NOT NULL,
	Stops TEXT[],
	Status TEXT,
	Price INT,
	Discount INT DEFAULT 0,
	PlaneID VARCHAR(6) DEFAULT 000000,
	WorkerID INT DEFAULT 000000000,
	PRIMARY KEY (FlightID),
	FOREIGN KEY (WorkerID) REFERENCES WORKER(WorkerID),
	FOREIGN KEY (PlaneID) REFERENCES PLANE(PlaneID)
);

CREATE TABLE BAG(
	BagID VARCHAR(10),
	Weight INT,
	Color TEXT,
	Price INT,
	CustomerID INT,
	FlightID VARCHAR(7),
	PRIMARY KEY (BagID),
	FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID),
	FOREIGN KEY (FlightID) REFERENCES FLIGHT(FlightID)
);

CREATE TABLE Customer_in_Flight(
	SeatNum INT,
	CustomerID INT,
	FlightID VARCHAR(7),
	FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID),
	FOREIGN KEY (FlightID) REFERENCES FLIGHT(FlightID),
	PRIMARY KEY (CustomerID, FlightID)
);



