// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TECAirAPI.Data;

namespace TECAirAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220329071213_BagController")]
    partial class BagController
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("TECAirAPI.Models.Bag", b =>
                {
                    b.Property<int>("BagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.Property<int>("WorkerID")
                        .HasColumnType("integer");

                    b.HasKey("BagID");

                    b.HasIndex("WorkerID");

                    b.ToTable("Bags");
                });

            modelBuilder.Entity("TECAirAPI.Models.Worker", b =>
                {
                    b.Property<int>("WorkerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("LastNameWorker")
                        .HasColumnType("text");

                    b.Property<string>("NameWorker")
                        .HasColumnType("text");

                    b.Property<string>("PassWorker")
                        .HasColumnType("text");

                    b.HasKey("WorkerID");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("TECAirAPI.Models.Bag", b =>
                {
                    b.HasOne("TECAirAPI.Models.Worker", "worker")
                        .WithMany("Bags")
                        .HasForeignKey("WorkerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("worker");
                });

            modelBuilder.Entity("TECAirAPI.Models.Worker", b =>
                {
                    b.Navigation("Bags");
                });
#pragma warning restore 612, 618
        }
    }
}
